// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: keyless_server.proto

package keyless

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// KeylessServiceService defines service.
type KeylessServiceService interface {
	KeylessRequest(ctx context.Context, req *KeylessRequestReq) (*KeylessRequestResp, error)

	KeylessReloadCerts(ctx context.Context, req *KeylessRequestReq) (*KeylessRequestResp, error)

	KeylessQueryMetricInfo(ctx context.Context, req *KeylessRequestReq) (*KeylessRequestResp, error)
}

func KeylessServiceService_KeylessRequest_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &KeylessRequestReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(KeylessServiceService).KeylessRequest(ctx, reqbody.(*KeylessRequestReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func KeylessServiceService_KeylessReloadCerts_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &KeylessRequestReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(KeylessServiceService).KeylessReloadCerts(ctx, reqbody.(*KeylessRequestReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func KeylessServiceService_KeylessQueryMetricInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &KeylessRequestReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(KeylessServiceService).KeylessQueryMetricInfo(ctx, reqbody.(*KeylessRequestReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// KeylessServiceServer_ServiceDesc descriptor for server.RegisterService.
var KeylessServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.mutual_https.keyless.KeylessService",
	HandlerType: ((*KeylessServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/KeylessRequest",
			Func: KeylessServiceService_KeylessRequest_Handler,
		},
		{
			Name: "/KeylessReloadCerts",
			Func: KeylessServiceService_KeylessReloadCerts_Handler,
		},
		{
			Name: "/KeylessQueryMetricInfo",
			Func: KeylessServiceService_KeylessQueryMetricInfo_Handler,
		},
		{
			Name: "/trpc.mutual_https.keyless.KeylessService/KeylessRequest",
			Func: KeylessServiceService_KeylessRequest_Handler,
		},
		{
			Name: "/trpc.mutual_https.keyless.KeylessService/KeylessReloadCerts",
			Func: KeylessServiceService_KeylessReloadCerts_Handler,
		},
		{
			Name: "/trpc.mutual_https.keyless.KeylessService/KeylessQueryMetricInfo",
			Func: KeylessServiceService_KeylessQueryMetricInfo_Handler,
		},
	},
}

// RegisterKeylessServiceService registers service.
func RegisterKeylessServiceService(s server.Service, svr KeylessServiceService) {
	if err := s.Register(&KeylessServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("KeylessService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedKeylessService struct{}

func (s *UnimplementedKeylessService) KeylessRequest(ctx context.Context, req *KeylessRequestReq) (*KeylessRequestResp, error) {
	return nil, errors.New("rpc KeylessRequest of service KeylessService is not implemented")
}
func (s *UnimplementedKeylessService) KeylessReloadCerts(ctx context.Context, req *KeylessRequestReq) (*KeylessRequestResp, error) {
	return nil, errors.New("rpc KeylessReloadCerts of service KeylessService is not implemented")
}
func (s *UnimplementedKeylessService) KeylessQueryMetricInfo(ctx context.Context, req *KeylessRequestReq) (*KeylessRequestResp, error) {
	return nil, errors.New("rpc KeylessQueryMetricInfo of service KeylessService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// KeylessServiceClientProxy defines service client proxy
type KeylessServiceClientProxy interface {
	KeylessRequest(ctx context.Context, req *KeylessRequestReq, opts ...client.Option) (rsp *KeylessRequestResp, err error)

	KeylessReloadCerts(ctx context.Context, req *KeylessRequestReq, opts ...client.Option) (rsp *KeylessRequestResp, err error)

	KeylessQueryMetricInfo(ctx context.Context, req *KeylessRequestReq, opts ...client.Option) (rsp *KeylessRequestResp, err error)
}

type KeylessServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewKeylessServiceClientProxy = func(opts ...client.Option) KeylessServiceClientProxy {
	return &KeylessServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *KeylessServiceClientProxyImpl) KeylessRequest(ctx context.Context, req *KeylessRequestReq, opts ...client.Option) (*KeylessRequestResp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/KeylessRequest")
	msg.WithCalleeServiceName(KeylessServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("mutual_https")
	msg.WithCalleeServer("keyless")
	msg.WithCalleeService("KeylessService")
	msg.WithCalleeMethod("KeylessRequest")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &KeylessRequestResp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *KeylessServiceClientProxyImpl) KeylessReloadCerts(ctx context.Context, req *KeylessRequestReq, opts ...client.Option) (*KeylessRequestResp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/KeylessReloadCerts")
	msg.WithCalleeServiceName(KeylessServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("mutual_https")
	msg.WithCalleeServer("keyless")
	msg.WithCalleeService("KeylessService")
	msg.WithCalleeMethod("KeylessReloadCerts")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &KeylessRequestResp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *KeylessServiceClientProxyImpl) KeylessQueryMetricInfo(ctx context.Context, req *KeylessRequestReq, opts ...client.Option) (*KeylessRequestResp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/KeylessQueryMetricInfo")
	msg.WithCalleeServiceName(KeylessServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("mutual_https")
	msg.WithCalleeServer("keyless")
	msg.WithCalleeService("KeylessService")
	msg.WithCalleeMethod("KeylessQueryMetricInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &KeylessRequestResp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
