// Code generated by MockGen. DO NOT EDIT.
// Source: ../keyless/keyless_server.trpc.go
//
// Generated by this command:
//
//	mockgen -source=../keyless/keyless_server.trpc.go -destination=../keyless/mock/keyless_server_mock.go -package=keyless
//

// Package keyless is a generated GoMock package.
package keyless

import (
	context "context"
	reflect "reflect"

	keyless "git.woa.com/johnnyqchen/mutual_https/infrastructure/protocol/keyless"
	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockKeylessServiceService is a mock of KeylessServiceService interface.
type MockKeylessServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockKeylessServiceServiceMockRecorder
}

// MockKeylessServiceServiceMockRecorder is the mock recorder for MockKeylessServiceService.
type MockKeylessServiceServiceMockRecorder struct {
	mock *MockKeylessServiceService
}

// NewMockKeylessServiceService creates a new mock instance.
func NewMockKeylessServiceService(ctrl *gomock.Controller) *MockKeylessServiceService {
	mock := &MockKeylessServiceService{ctrl: ctrl}
	mock.recorder = &MockKeylessServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeylessServiceService) EXPECT() *MockKeylessServiceServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockKeylessServiceService) ISGOMOCK() struct{} {
	return struct{}{}
}

// KeylessQueryMetricInfo mocks base method.
func (m *MockKeylessServiceService) KeylessQueryMetricInfo(ctx context.Context, req *keyless.KeylessRequestReq) (*keyless.KeylessRequestResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeylessQueryMetricInfo", ctx, req)
	ret0, _ := ret[0].(*keyless.KeylessRequestResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeylessQueryMetricInfo indicates an expected call of KeylessQueryMetricInfo.
func (mr *MockKeylessServiceServiceMockRecorder) KeylessQueryMetricInfo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeylessQueryMetricInfo", reflect.TypeOf((*MockKeylessServiceService)(nil).KeylessQueryMetricInfo), ctx, req)
}

// KeylessReloadCerts mocks base method.
func (m *MockKeylessServiceService) KeylessReloadCerts(ctx context.Context, req *keyless.KeylessRequestReq) (*keyless.KeylessRequestResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeylessReloadCerts", ctx, req)
	ret0, _ := ret[0].(*keyless.KeylessRequestResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeylessReloadCerts indicates an expected call of KeylessReloadCerts.
func (mr *MockKeylessServiceServiceMockRecorder) KeylessReloadCerts(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeylessReloadCerts", reflect.TypeOf((*MockKeylessServiceService)(nil).KeylessReloadCerts), ctx, req)
}

// KeylessRequest mocks base method.
func (m *MockKeylessServiceService) KeylessRequest(ctx context.Context, req *keyless.KeylessRequestReq) (*keyless.KeylessRequestResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeylessRequest", ctx, req)
	ret0, _ := ret[0].(*keyless.KeylessRequestResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeylessRequest indicates an expected call of KeylessRequest.
func (mr *MockKeylessServiceServiceMockRecorder) KeylessRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeylessRequest", reflect.TypeOf((*MockKeylessServiceService)(nil).KeylessRequest), ctx, req)
}

// MockKeylessServiceClientProxy is a mock of KeylessServiceClientProxy interface.
type MockKeylessServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockKeylessServiceClientProxyMockRecorder
}

// MockKeylessServiceClientProxyMockRecorder is the mock recorder for MockKeylessServiceClientProxy.
type MockKeylessServiceClientProxyMockRecorder struct {
	mock *MockKeylessServiceClientProxy
}

// NewMockKeylessServiceClientProxy creates a new mock instance.
func NewMockKeylessServiceClientProxy(ctrl *gomock.Controller) *MockKeylessServiceClientProxy {
	mock := &MockKeylessServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockKeylessServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeylessServiceClientProxy) EXPECT() *MockKeylessServiceClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockKeylessServiceClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// KeylessQueryMetricInfo mocks base method.
func (m *MockKeylessServiceClientProxy) KeylessQueryMetricInfo(ctx context.Context, req *keyless.KeylessRequestReq, opts ...client.Option) (*keyless.KeylessRequestResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeylessQueryMetricInfo", varargs...)
	ret0, _ := ret[0].(*keyless.KeylessRequestResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeylessQueryMetricInfo indicates an expected call of KeylessQueryMetricInfo.
func (mr *MockKeylessServiceClientProxyMockRecorder) KeylessQueryMetricInfo(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeylessQueryMetricInfo", reflect.TypeOf((*MockKeylessServiceClientProxy)(nil).KeylessQueryMetricInfo), varargs...)
}

// KeylessReloadCerts mocks base method.
func (m *MockKeylessServiceClientProxy) KeylessReloadCerts(ctx context.Context, req *keyless.KeylessRequestReq, opts ...client.Option) (*keyless.KeylessRequestResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeylessReloadCerts", varargs...)
	ret0, _ := ret[0].(*keyless.KeylessRequestResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeylessReloadCerts indicates an expected call of KeylessReloadCerts.
func (mr *MockKeylessServiceClientProxyMockRecorder) KeylessReloadCerts(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeylessReloadCerts", reflect.TypeOf((*MockKeylessServiceClientProxy)(nil).KeylessReloadCerts), varargs...)
}

// KeylessRequest mocks base method.
func (m *MockKeylessServiceClientProxy) KeylessRequest(ctx context.Context, req *keyless.KeylessRequestReq, opts ...client.Option) (*keyless.KeylessRequestResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeylessRequest", varargs...)
	ret0, _ := ret[0].(*keyless.KeylessRequestResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeylessRequest indicates an expected call of KeylessRequest.
func (mr *MockKeylessServiceClientProxyMockRecorder) KeylessRequest(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeylessRequest", reflect.TypeOf((*MockKeylessServiceClientProxy)(nil).KeylessRequest), varargs...)
}
